# Generated by Django 5.2.7 on 2025-10-02 05:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Asignatura',
            fields=[
                ('asignatura_id', models.AutoField(primary_key=True, serialize=False)),
                ('descripcion', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Pregunta',
            fields=[
                ('pregunta_id', models.AutoField(primary_key=True, serialize=False)),
                ('enunciado', models.TextField()),
                ('numero', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Partida',
            fields=[
                ('partida_id', models.AutoField(primary_key=True, serialize=False)),
                ('descripcion', models.CharField(max_length=200)),
                ('asignatura', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='partidas', to='app.asignatura')),
            ],
        ),
        migrations.CreateModel(
            name='Opcion',
            fields=[
                ('opcion_id', models.AutoField(primary_key=True, serialize=False)),
                ('opcion', models.TextField()),
                ('media_url', models.URLField(blank=True, null=True)),
                ('es_correcta', models.BooleanField(default=False)),
                ('pregunta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='opciones', to='app.pregunta')),
            ],
        ),
        migrations.CreateModel(
            name='ProgramaAnalitico',
            fields=[
                ('linea_educativa_id', models.AutoField(primary_key=True, serialize=False)),
                ('titulo', models.CharField(max_length=200)),
                ('contexto', models.TextField()),
                ('asignatura', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='programas_analiticos', to='app.asignatura')),
            ],
        ),
        migrations.CreateModel(
            name='Unidad',
            fields=[
                ('unidad_id', models.AutoField(primary_key=True, serialize=False)),
                ('numero_unidad', models.IntegerField()),
                ('descripcion', models.CharField(max_length=200)),
                ('num_preguntas', models.IntegerField()),
                ('programa_analitico', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='unidades', to='app.programaanalitico')),
            ],
        ),
        migrations.AddField(
            model_name='pregunta',
            name='unidad',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='preguntas', to='app.unidad'),
        ),
    ]
