# Generated by Django 5.2.7 on 2025-10-03 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_carrera_asignatura_carrera'),
    ]

    operations = [
        migrations.AddField(
            model_name='pregunta',
            name='explicacion',
            field=models.TextField(blank=True, help_text='Explicación detallada de la respuesta correcta', null=True),
        ),
    ]
